{
 "title": "Vantage API Reference Dashboard",
 "description": "Reference Implementation for available endpoints in the vantage-exporter",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "skills", "query": { "query": "" } }
  ]
 },
 "panels": [
  {
   "title": "Vantage API Reference Dashboard",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true
  },
  { "title": "Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Total Skills",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "count(vantage_skill_info)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Skills & TX count",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
   "targets": [
    {
     "expr": "group by (skill_name) (vantage_skill_info{skill_name=~\"$skills\"} * 0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Completed Transactions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum by (skill_name, status) (vantage_completed_transactions_total * on(skill_id) group_left(skill_name) vantage_skill_info{skill_name=~\"$skills\"})\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active TXs over time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "sum by (skill_name) (vantage_active_transaction * on(skill_id) group_left(skill_name) vantage_skill_info{skill_name=~\"$skills\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Skills", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Skill Details",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {}
   ]
  },
  { "title": "Transactions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Skill TXs",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "targets": [
    {
     "parser": "backend",
     "source": "url",
     "type": "json",
     "url": "/transaction-details?skills=${skills}",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "Compare TX",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "targets": [
    {
     "parser": "backend",
     "source": "url",
     "type": "json",
     "url": "/transaction-details?skills=${skills}",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  }
 ]
}